### PR TITLE
adding config property to needsPatch conditional

### PR DESCRIPTION
**Pull request by ivynye**

### CODE REVIEW

**Comment by timruffles** [comment]
Would it be possible to document this too please?

**Comment by ivynye** [comment]
Add details to readme.md under shim behaviour (instead of config) to deter new users from implementing the force option.

**Comment by timruffles** [comment]
Sorry to be really annoying, but I've just realised that it makes a lot of sense to *only* sniff if your new flag isn't there:

```js
var needsPatch = config.needsPatch == null
  ? !(dragDiv || evts) || /iPad|iPhone|iPod|Android/.test(navigator.userAgent) 
  : Boolean(config.needsPatch);
```

**Comment by reppners** [comment]
Closing because this is also contained in the rewrite now released. https://www.npmjs.com/package/mobile-drag-drop

**Pull request closed without merging**
