### PR TITLE
Umd support

### PR DESCRIPTION
**Pull request by reppners**
These changes introduce UMD support with declaration file enhancement by using rollup on the typescript ES2015 module output. 

Basically it does the same as PR #98 (kudos to @dpogue for paving the path) but without removing the  toolchain used for development/release workflow.

Will test the changes in a webpack-based project tomorrow. Global usage in demo is working fine.

- [x] global
- [x] webpack
- [x] systemjs / jspm

related issues #83, #94

### CODE REVIEW

**Comment by timruffles** [comment]
Looks great, and I'll also second your thanks to @dpogue for his excellent work!

**Comment by reppners** [comment]
Thx. Just recognized that rollup with typescript plugin won't resolve const enum's which raises output size. Looks like sourcemaps can be maintained by using another plugin and build with tsc upfront which is needed anyways for having declaration files.

https://github.com/rollup/rollup-plugin-typescript/issues/28#issuecomment-242999859

**Comment by dpogue** [comment]
Just checked the [rollup config](https://github.com/dpogue/ios-html5-drag-drop-shim/blob/buildsystem-release/rollup.config.js#L12) on my branch and it looked like I had to pull in [rollup-plugin-sourcemaps](https://github.com/maxdavidson/rollup-plugin-sourcemaps) (Although worth noting that I was running TypeScript with `tsc` instead of through rollup-plugin-typescript)

Currently we are getting a warning in WebPack about sourcemaps:
```
WARNING in ./~/drag-drop-polyfill/release/drag-drop-polyfill.min.js
(Emitted value instead of an instance of Error) Cannot find SourceMap drag-drop-polyfill.min.js.map: Error: Can't resolve './drag-drop-polyfill.min.js.map' in '<PROJECT>/node_modules/drag-drop-polyfill/release'
 @ ./demo/app.ts 11:0-54
```

**Comment by reppners** [comment]
Build now uses `tsc` followed by rollup with `rollup-plugin-sourcemaps`. Release files now include sourcemaps.

**Comment by reppners** [comment]
Last tests with jspm/systemjs and declaration file support were succesful. `export as namespace` works as intended.

**Pull request merged**
