### PR TITLE
consolidate with rewrite

### PR DESCRIPTION
**Pull request by reppners**
Merging in the refactoring-branch of the typescript rewrite to start work on consolidating and merging with latest improvements and bug-fixes of the master branch. All further work is based on this branch.

@timruffles @xStrom 

As mentioned in #44 I did a few changes to get started:

- [x] use tsconfig.json for TS config instead of grunt task config
- [x] introduce TSLint
- [x] implement setDragImage() in rewrite
- [x] make sure latest bugfixes either are not needed in first place or are applied to rewrite
  - [x] #57 - Fixed.
  - [x] #54 - Fixed. ~~Double check but since I'm using that lib too and have no issues I guess its fixed.~~
  - [x] #49 - Deliberately requiring a call to `Initialize()` because of reasons like that.
  - [x] #59 - Fixed.
  - [x] #58 - Fixed.
  - [x] #56 - This needs to be implemented.
  - [x] #55 - Fixed.
  - [x] #52, #53 - Fixed by enabling override hooks: 1dfd213
  - [x] #51 - Fixed.
  - [x] #37 - Fixed.
  - [x] #60 - Fixed.
  - [x] #62 - Fixed.
  - [x] #50 - Should be fixed. Double check.
  - [x] #23 - Fixed.
  - [x] #40 - ~~The only browser I could not test is IEMobile. Could be it has native support?~~ IEMobile has native support. Edge-Browser is untested yet.
  - [x] #42 - Fixed.
- [x] Fixed. Current Mobile Safari seems to behave better now when `shrink-to-fit=no` is specified. ~~find solution for Safari 9 zooming the whole webpage when a drag item reaches right edge of the viewport (they changed something from v8 to v9 that I couldn't come up with a solution yet), more specifically it seems to occur when drag starts and that the drag item initially is overlapping the right edge of the viewport. Maybe this can be hacked by initializing it in a way that makes sure its not overlapping the right edge.~~
- [x] refactor code to allow hook for customizing drag start conditions
- [x] refactor code to allow hook for default action when drag was not started
- [x] refactor code to allow hook for scrolling a container or viewport when dragging close to an edge
- [x] read transition duration for snapback transitions from drag image style instead of hardcoding it
- [x] fix snapback transition target coordinates
- [x] scrolling when dragging close to edges implemented as plugin
- [ ] update README
 - [x] api
 - [ ] usage example
 - [ ] known issues and limitations section
- [ ] cleanup demo/test page and provide usage examples with code snippets
  - [ ] examples of drag and drop with different effects
  - [ ] example of nested draggables
  - [ ] example of using custom drag start condition override
    - [ ] showcase limitation when doing deferred drag start
  - [ ] example of implementing drag-handle
  - [ ] example of using scroll plugin
- [x] defer UMD support until TypeScript 2.0
- [ ] #30 rename to `drag-drop-polyfill`
- [x] #63 implement option to force the polyfill to be applied

### CODE REVIEW

**Comment by reppners** [comment]
As far as I can tell all improvements and bugfixes that went into master are now also implemented in the rewrite.

The latest commits also add override hooks:
* drag start condition
* default action when no drag was started
* drag image translate

The latter enabled me to move all scrolling related code to a plugin, which now is able to handle nested scrollable containers and has a velocityFn so based on how much you get close to a scrollable container's edge will increase the scrolling speed. It still has its rough edges and corner cases but its ok for most usage scenarios.

The other two hooks are primarily focused on letting polyfill users do their custom thing when they need to. Whilst implementing them I discovered a few things that I wanted to point out here:
* Not canceling `touchstart/touchmove` immediately will lead to problems once a hook decides to start the drag operation.
  * When doing a deferred drag start, a scrolling of the browser might be initiated and you won't be able to stop it. Also the translate of the drag image will not work right. It feels like a broken parallax-effect.
  * This happens especially often when the site is zoomed-in because then the browser most likely will start scrolling if not canceling the initial `touchstart/touchmove`.
  * The rule is: Once the browser starts scrolling to can't stop it. If a drag operation is then started it is broken.

Why NOT cancel the initial `touchstart` then?
* No custom code for triggering the default action if the drag was not started (which kind of obsoletes the default action override hook)
* Native scrolling will just work. You can make list items draggable by using a dedicated drag handle.

In my opinion this outweighs the possibly buggy behavior that results from a deferred drag operation start. Because most of these drag start conditions that need to defer the decision are doing so because they need to be able to scroll and would be better off by implementing a dedicated drag handle because its also the most obvious thing from a users perspective. If you have a drag start condition that can be determined immediately by looking at the initial `touchstart/touchmove` it won't produce any buggy behavior.

**Comment by xStrom** [comment]
Really nice work by the looks of it!

Regarding myself, the plan is to do some review/testing tomorrow.

**Comment by timruffles** [comment]
Fantastic stuff!

**Comment by reppners** [comment]
Thx :) As for the rename - what do you think about `drag-drop-polyfill`?

**Comment by timruffles** [comment]
Sounds good to me!

**Comment by xStrom** [comment]
I have no opinion about the name. All of them work for me.

**Comment by reppners** [comment]
Ok so lets name it `drag-drop-polyfill`.

How do we handle the rename?

To achieve a hassle-free publishing procedure I would like to include the release workflow as script. A quick research showed that npm already has some handy command: https://docs.npmjs.com/cli/version

But to do npm and bower simultaneously https://github.com/vojtajina/grunt-bump seems to be a good alternative, too.

**Comment by xStrom** [comment]
Having a script do the release workflow seems like a good idea to me. Unfortunately I don't have any experience with publishing on npm/bower, so I don't have any opinion on how to exactly do it.

I'm not really a fan of compiled code under source control though. The diffs aren't understandable, malicous or buggy code can get through code review due to this, and it's just noise in general. Is that the common way of doing it for npm/bower?

If we do keep compiled code under source control, then I suggest we update it only with the release script and accept commits that modify these compiled files only from collaborators.

**Comment by reppners** [comment]
> I'm not really a fan of compiled code under source control though. The diffs aren't understandable, malicous or buggy code can get through code review due to this, and it's just noise in general. Is that the common way of doing it for npm/bower?

For the release code this is true, yes. Otherwise you put the burden of compiling the package to the user, who might not uses any of the build setup infrastructure required for the package so they can't really use it easily.

Thats why there is a `release` folder in the project setup where the build results go. This is the folder that the users will get when installing the package. Everything else will be omitted so the footprint of files is as low as possible. Installing the package should not fetch demo files and source files. Those are only needed when developing.

> If we do keep compiled code under source control, then I suggest we update it only with the release script and accept commits that modify these compiled files only from collaborators.

Yes, if people contribute, they contribute to the src files. Even when they commit release files they will be cleaned and overwritten once a maintainer does the release after merging pull requests.

The workflow would be:
* merge changes and make sure everything is fine (git status is clean after that)
* start the release script which will build, lint, run tests and after success trigger the version bump
* version bump does raise version numbers, commit the release-code, make a tag and push it -> released.

Since committing/pushing is only possible for maintainers it is safe.

Right now this is manual work, so its prone to forget something.

**Comment by timruffles** [comment]
We could just push each release as a history-less commit and tag them to
avoid them being garbage collected.

**Comment by timruffles** [comment]
:shipit: Want a bit of a hand getting this shipped?

**Comment by reppners** [comment]
Yes, indeed. I'm very busy at the moment and will be for the coming weeks.

**Comment by bartvanremortele** [comment]
Hi, Any news on when this refactoring will be finished?

**Comment by reppners** [comment]
I want to get this done in the next two weeks but I can't promise anything because I'm very short of time.

Having said that you can expect very few breaking changes if any so you can directly reference this branch in your project until it is out officially.

**Comment by kamelkev** [comment]
Woah! So much is happening here I can't even keep up.

I see tons of bugfixes and things, but I just realized that for some reason ticket #5 is randomly closed. Technically cross-frame dragging is part of the html5 spec. It works rather well on the desktop.

@timruffles can you please re-open issue #5? This project is literally the only one where there is a hope of getting that support in a polyfill.

**Comment by felixruponen** [comment]
Any news about when this might be merged?

**Comment by reppners** [comment]
@felixruponen I'm still drowning in my day-job workload so I can't tell any timeframe. The remaining work is mostly around docs and demos though.

**Comment by reppners** [comment]
DISCLAIMER: The latest commits introduce a breaking change for anyone who uses this branch because of changed filenames.

Only docs, demos and releasing left to do.

For the release workflow https://github.com/vojtajina/grunt-bump seems to be the best solution because it can handle bower and npm. The task can raise version numbers and prepare a commit. Pushing should be done manually after checking if everything is ok.

The master-branch should be preserved as v1-branch before merging this pull-request. We should resolve all pull-request before doing this to have a clean state.

**Comment by reppners** [comment]
Merged to continue work in the dedicated rewrite branch as its now about demos, documentation and bug-fixes. Remaining work is documented here https://github.com/timruffles/ios-html5-drag-drop-shim/issues/69. Continuing with preparing the first beta release now.

**Comment by reppners** [comment]
First beta release based on the rewrite branch is available https://github.com/timruffles/ios-html5-drag-drop-shim/releases/tag/v2.0.0-beta.0

**Comment by timruffles** [comment]
This looks amazing!

What are next steps - really want to see your great work get released. Anyone able to help @xStrom @reppners @nathanbedford ?

**Comment by reppners** [comment]
TODOs are tracked in #69.

I had started work on demos but lost all the progress due to a corrupted disk  :-/

What I really would like to be completed prior to release is the upgrade to TypeScript 2.x to support UMD and proper automatic generation of declaration files.

#87 has already started the upgrade.

So basically it's about making it easy to consume the polyfill.

**Comment by xStrom** [comment]
Documentation/example work probably shouldn't be blocking the release. However I agree that there's value in waiting for the TS 2.x / module work.

I'll try to find some time to help see the 2.0 branch into a releasable state.

**Pull request merged**
