### PR TITLE
Initial stab at a UMD-compatible structure

### PR DESCRIPTION
**Pull request by dpogue**
Probably not safe to merge as-is, but I took a stab at porting to a TypeScript UMD-style module

Refs #83

### CODE REVIEW

**Comment by reppners** [comment]
Thx for your effort 👍 very much appreciated!

I'm moving atm and there's no internet connection yet nor a desk or anything to work at home so I can't review it right now ;) will take at least a week till I can get back to this.

**Comment by dpogue** [comment]
No worries, ignore this until you're all unpacked and settled in :)

I did notice one major problem with this branch when combined with WebPack 2, namely that WebPack can't handle TypeScript-output UMD modules and turns it into a `require('.')` call that breaks the entire bundle.

As a workaround for that, I made a branch that's using rollup.js to generate the UMD module:
https://github.com/timruffles/ios-html5-drag-drop-shim/compare/rewrite...dpogue:buildsystem
Don't really want to open a PR that replaces the entire build system without discussing it though 😛 

I've confirmed that it works with WebPack (although the sourcemaps for the min.js file are causing problems that I need to look into) and will try to do some more testing with the included demo/test cases.

**Comment by reppners** [comment]
Finally had time to look at the changes needed for full UMD-support (AMD, CommonJS, Global) and TypeScript's UMD-module does not support a globals fallback. Further it needs manual additions to the created `d.ts`-files..

That's a bummer.. Should've read about the detailed capabilities of TypeScript's UMD support earlier. Having to fiddle with the `d.ts`-files each time a release is made is not really what I was aiming for. Also dead-code elimination with uglify does not work once the code is wrapped in the UMD function.

Wishlist
- supports AMD, CommonJS, Global
- automatically enhance `d.ts`-file(s) with needed `export as namespace` line
- does not interfere with minification

With this in mind I think TypeScript's UMD setting is not the right thing for this library. Rather we need some build step on the `.js` output that adds the appropriate UMD wrapper function and also adds the extra line to the `d.ts`

Another approach would be to generate separate build outputs (Global, CommonJS, ES2015).

**Comment by timruffles** [comment]
Would this be solved by using webpack, browserify etc after TypeScript?

**Comment by dpogue** [comment]
Yes (well, I used rollup to generate the UMD module): https://github.com/timruffles/ios-html5-drag-drop-shim/compare/rewrite...dpogue:buildsystem

**Comment by timruffles** [comment]
@dpogue so this PR is looking good to you? @reppners anything else required?

**Comment by dpogue** [comment]
No, I'll open a new PR with the rollup-based buildsystem: #98

**Pull request closed without merging**
