### PR TITLE
Keep initial drag position

### PR DESCRIPTION
**Pull request by azatoth**
When dragging an object, keep the initial drag position instead of
center the drag image around the pointer.

also keep the object inside the screen until we really try to go outside.

### CODE REVIEW

**Comment by timruffles** [comment]
Thanks for this! Would it be possible to provide a bit more detail. Is it likely to affect existing users adversely?

**Comment by azatoth** [comment]
My problem was that we were dragging a table row which occupies ⅓rd the width of the screen, and it can be dragged and dropped into a list to the right. When starting dragging, the row centers around where you drag, so regardless of where you drag from, you end up with half of the row to the right. Directly when you move the row and it's right edge goes pass the browser, it will start rescale the unit (tested in chrome).

to have the object dragged where you press is logical, and unless it's possible to prevent screen swapping, the object should be kept in the browser window while you are still dragging in the browser window.

**Comment by azatoth** [comment]
As I feel I've failed to explain the issue I had, I've created http://embed.plnkr.co/MMPicFqjxvEC4sPGRXr5/ to show what problems I had. the screen scaling issue I had is not reproducible so I assume that's related to some funky css we are using :/

**Comment by azatoth** [comment]
I realize my second problem with the zooming viewport was related to http://stackoverflow.com/questions/14270084/overflow-xhidden-doesnt-prevent-content-from-overflowing-in-mobile-browsers and I assume we could omit the viewport limit in the PR.

**Comment by azatoth** [comment]
I did decide to remove the out of bounds check and only include the drag position code in this pull request.

**Comment by reppners** [comment]
Closing because this is already contained in the rewrite now released. https://www.npmjs.com/package/mobile-drag-drop

**Pull request closed without merging**
